{
 "title": "Netology Homework",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU utilization (100% - Idle)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node\",mode=\"idle\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem free space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_filesystem_free_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPULA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU AVG 1 min"
    },
    {
     "expr": "100 - (avg by (instance)(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU AVG 5 min"
    },
    {
     "expr": "100 - (avg by (instance)(rate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node\",mode=\"idle\"}[15m])) * 100)",
     "legendFormat": "CPU AVG 15 min"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}