stages:
  - build
  - deploy

build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n "json_key:${CI_REGISTRY_KEY}" | base64 | tr -d '\n' )\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
        --destination "${CI_REGISTRY}/hello:gitlab-${CI_COMMIT_SHORT_SHA}"

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  environment:
    name: production
  script:
    - kubectl config get-contexts
    - kubectl config use-context ${CI_PROJECT_PATH}:mykubagent
    - cat k8s.yaml | sed -e "s,__IMAGE__,${CI_REGISTRY}/hello:gitlab-${CI_COMMIT_SHORT_SHA}," | kubectl -n hello-world apply -f -
  only:
    - main
