---
  el:
    hosts:
      centos:
        ansible_connection: docker
  deb:
    hosts:
      debian:
        ansible_connection: docker
  fed:
    hosts:
      fedora:
        ansible_connection: docker
  local:
    hosts:
      localhost:
        ansible_connection: local
