---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Clickhouse | Restart service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - block:
        - name: Clickhouse | Get distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
            dest: "./{{ item }}-{{ clickhouse_version }}.deb"
          with_items: "{{ clickhouse_packages }}"

      rescue:
        - name: Clickhouse | Get distrib (rescue)
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"

    - name: Clickhouse | Install packages
      become: true
      ansible.builtin.apt:
        deb: "./{{ item }}-{{ clickhouse_version }}.deb"
      with_items: "{{ clickhouse_packages }}"
      notify: Clickhouse | Restart service

    - name: Clickhouse | Flush handlers
      meta: flush_handlers

    - name: Clickhouse | Create database
      ansible.builtin.command: "clickhouse-client -q 'create database {{ db_name }};'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  tags: vector

  handlers:
    - name: Vector | Restart Service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
        daemon_reload: true

  tasks:
#    - block:
    - name: Vector | Get distrib
      tags: vector
      ansible.builtin.get_url:
        url: "{{ vector_url }}/{{ vector_version }}/{{ vector_package }}_{{ vector_version }}-1_amd64.deb"
        dest: "./{{ vector_package }}-{{ vector_version }}.deb"

    - name: Vector | Install package
      tags: vector
      become: true
      ansible.builtin.apt:
        deb: "./{{ vector_package }}-{{ vector_version }}.deb"

    - name: Vector | Configure | ensure what config directory exists
      tags: vector
      file:
        path: "{{ vector_config_dir }}"
        state: directory
        mode: 0755

    - name: Vector | Configure | Template config
      tags: vector
      ansible.builtin.template:
        src: ./template/my_vector_cfg.tmpl
        mode: 0644
        dest: "{{ vector_config_dir }}/vector.yml"

    - name: Vector | Prepare and setup unit from template
      tags: vector
      become: true
      ansible.builtin.template:
        src: ./template/my_vector_service.tmpl
        dest: /etc/systemd/system/vector.service
        mode: 0644
      notify: Vector | Restart Service

    - name: Vector | Flush handlers
      tags: vector
      meta: flush_handlers

    - name: Vector | Create Log Dir
      tags: vector
      become: true
      ansible.builtin.file:
        state: directory
        path: "{{ vector_log_dir }}"
        mode: u=rwx,g=rwx,o=rwx

# --- Nginx ---

- name: Lighthouse | Install nginx
  hosts: lighthouse

  handlers:
    - name: Lighthouse | Nginx | Restart Service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted

  tasks:
    - name: Lighthouse | Nginx | Install from apt
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      notify: Lighthouse | Nginx | Restart Service

# --- Lighthouse ---

- name: Install lighthouse
  hosts: lighthouse

  handlers:
    - name: Lighthouse | Restart Nginx Service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted

  pre_tasks:
    - name: Lighthouse | Install unzip
      become: true
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: true

  tasks:
    - name: Lighthouse | Download zip package
      ansible.builtin.get_url:
        url: "{{ lighthouse_zip_url }}/master.zip"
        dest: "./lighthouse.zip"
        mode: "0644"

    - name: Lighthouse | Unarch zip package to nginx homedir
      become: true
      ansible.builtin.unarchive:
        src: ./lighthouse.zip
        dest: /var/www/html/
        remote_src: true
      notify: Lighthouse | Restart Nginx Service

    - name: Make nginx config
      become: true
      ansible.builtin.template:
        src: ./template/default.tmpl
        dest: /etc/nginx/sites-enabled/default
        mode: "0644"
      notify: Lighthouse | Restart Nginx Service

    - name: Lighthouse | Delete zip package
      ansible.builtin.file:
        path: "./lighthouse.zip"
        state: absent
